### ISSUE TITLE
Установить IDE 

### ISSUE THREAD

**Issue by serykhelena** [lsd-maddrive/mnist_recognition#2]
Нужно установить IDE для разработки на Python. 
Я бы рекомендовала [VS Code](https://code.visualstudio.com/download), но если есть какие-то свои предпочтения, то можно использовать и другую IDE

**Comment by serykhelena** [comment]
@MarinaKupetskova что с задачкой? Можно закрывать?

**Comment by MarinaKupetskova** [comment]
> @MarinaKupetskova что с задачкой? Можно закрывать?

Да, можно , закрываю
